version: "3"
services:
  db:
    image: mongo:latest # Use the official MongoDB image from Docker Hub
    container_name: my-mongodb-container
    ports:
      - "27017:27017" # Map the MongoDB port to the host machine
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin11
      MONGO_INITDB_ROOT_PASSWORD: 0000
      MONGO_INITDB_DATABASE: MlopsdeadinsideDB
    volumes:
      - ./mongodb-data:/data/db # Store MongoDB data in a local directory

      
  app:
    image: mlopsdeadinside/ca4:v0 # Use the image from Docker Hub
    platform: linux/amd64
    container_name: flask
    ports:
      - "80:80"
    depends_on:
      - db # Ensure that the database service is started before the app service

